### ISSUE TITLE
Wrong type annotation for callbacks

### ISSUE THREAD

**Issue by polux** [Scarygami/dart_hangouts_api#3]
StateChangedHandler.add, StateChangedHandler.remove, ParticipantsAddedHandler.add, ParticipantsAddedHandler.remove .... should take callbacks that return void, nor Function.

**Comment by Scarygami** [comment]
Fixed in https://github.com/Scarygami/dart_hangouts_api/commit/0817ca2f2c87993b907777707ff5c77fc7954966 and published with version 0.2.3

That was a misconception on my side how function parameters worked in Dart, and I never noticed the issue because I used the callbacks with inline functions only:

    hapi.data.onStateChanged.add((StateChangedEvent e) {
       ...
    });

Thanks for the info :)

**Comment by polux** [comment]
Wow that was fast! Thanks!
